# This is a sample YAML file; fix or create resume.yaml according to your own information.
#
# IMPORTANT: all keys must be in camelCase

profile:
  name: John Smith # This will be the main title
  badges: # List of badges to display next to main title
  - text: Developer # Badge text
    color: bg-blue-500 # tailwind.css background color
  - text: Open Source Contributor
    color: bg-green-500
  description: Experienced software developer with a passion for open source projects. Skilled in Python, JavaScript, and cloud technologies.
  phone: +1 555-123-4567
  email: john.smith@example.io
  location: San Francisco, CA, USA
  websites:
    - https://johnsmith.dev
    - https://linkedin.com/in/johnsmith

education:
  - backgroundColor: bg-blue-600
    borderColor: border-blue-800
    institution: University of California, Berkeley
    badge: # Badge to display at header of the card
      text: B.Sc.
      color: bg-blue-500
    degree: Bachelor of Science in Computer Science
    description: Graduated with honors, focusing on software engineering and algorithms.
    gpa: 3.8/4.0

skills:
  - backgroundColor: bg-green-600
    borderColor: border-green-800
    name: Go
    badge:
      text: Expert
      color: bg-green-500
    description: Extensive experience in building scalable backend services using Go.
  - backgroundColor: bg-yellow-600
    borderColor: border-yellow-800
    name: Vue.js
    badge:
      text: Proficient
      color: bg-green-500
    description: Developed multiple single-page applications using Vue.js framework.

workExperiences:
  - backgroundColor: bg-green-600
    borderColor: border-green-800
    company: Tech Innovators Inc.
    badge:
      text: Full-time
      color: bg-green-500
    position: Senior Software Engineer
    description: Led a team of developers in creating cloud-native applications and microservices.
    location: Chicago, IL, USA
    startDate: Jun 2018
    endDate: Present
  - backgroundColor: bg-blue-600
    borderColor: border-blue-800
    company: Web Solutions LLC
    badge:
      text: Internship
      color: bg-blue-500
    position: Software Engineering Intern
    description: Assisted in developing web applications and improving user interfaces.
    location: New York, NY, USA
    startDate: Jun 2014
    endDate: Aug 2014

projects:
  - backgroundColor: bg-blue-600
    borderColor: border-blue-800
    name: Open Source Library XYZ
    badge:
      text: Maintainer
      color: bg-blue-500
    description: Created and maintained an open-source library for data processing, used by thousands of developers worldwide.
    startDate: Jan 2019
    endDate: Present
    websites:
      - https://johnsmith.dev/xyz
    stacks:
      - Python
      - Docker
      - Kubernetes
  - backgroundColor: bg-green-600
    borderColor: border-green-800
    name: Personal Portfolio Website
    badge:
      text: Creator
      color: bg-green-500
    description: Developed a personal portfolio website to showcase projects and skills.
    startDate: May 2020
    endDate: Jun 2020
    websites:
      - https://johnsmith.dev
    stacks:
      - HTML
      - CSS
      - JavaScript
      - Vue.js
