# This is a sample yaml!
# Create new yaml according to your own information and language, then configure on `/app/app.config.ts`.
# 
# IMPORTANT: all keys must be in camelCase.

profile:
  name: John Smith # This will be the main title
  badges: # List of badges to display next to main title
  - text: Developer # Badge text
    color: bg-blue-500 # tailwind.css background color
  - text: Open Source Contributor
    color: bg-green-500
  description: Experienced software developer with a passion for open source projects. Skilled in Python, JavaScript, and cloud technologies.
  phone: +1 555-123-4567
  email: john.smith@example.io
  location: San Francisco, CA, USA
  websites:
    - https://johnsmith.dev
    - https://linkedin.com/in/johnsmith

education:
  - backgroundColor: bg-blue-50/50
    borderColor: border-blue-200
    institution: University of California, Berkeley
    degree: Bachelor of Science in Computer Science
    description: Graduated with honors, focusing on software engineering and algorithms.
    gpa: 3.8/4.0

skills:
  - backgroundColor: bg-green-50/50
    borderColor: border-green-200
    name: Programming Languages
    description: Go, Python, Vue.js
  - backgroundColor: bg-green-50/50
    borderColor: border-green-200
    name: Cloud & DevOps
    description: Docker, Kubernetes, AWS
  - backgroundColor: bg-amber-50/50
    borderColor: border-amber-200
    name: Database
    description: MySQL, MongoDB, PostgreSQL

workExperiences:
  - backgroundColor: bg-green-50/50
    borderColor: border-green-200
    company: Tech Innovators Inc.
    position: Senior Software Engineer
    description: Led a team of developers in creating cloud-native applications and microservices.
    location: Chicago, IL, USA
    startDate: Jun 2018
    endDate: Present
    achievements:
      - name: "Project: Cloud Migration"
        description: 
          - Developed a microservices architecture that improved system scalability.
          - Implemented CI/CD pipelines, reducing deployment time by 50%.
        stacks:
          - Go
          - Docker
          - Kubernetes
      - name: "Project: Real-time Analytics"
        description: 
          - Designed and implemented a real-time analytics platform using Go and Kafka.
          - Enhanced data processing speed by 30% through optimized algorithms.
        stacks:
          - Go
          - Kafka
          - PostgreSQL
  - backgroundColor: bg-blue-50/50
    borderColor: border-blue-200
    company: Web Solutions LLC
    position: Software Engineering Intern
    description: Assisted in developing web applications and improving user interfaces.
    location: New York, NY, USA
    startDate: Jun 2014
    endDate: Aug 2014
    achievements:
      - name: "Project: E-commerce Website"
        description: 
          - Contributed to the development of a responsive e-commerce website using Vue.js.
          - Improved user experience by implementing dynamic content loading.
        stacks:
          - Vue.js
          - HTML
          - CSS

personalProjects:
  - backgroundColor: bg-blue-50/50
    borderColor: border-blue-200
    name: Open Source Library XYZ
    description: Created and maintained an open-source library for data processing, used by thousands of developers worldwide.
    websites:
      - https://johnsmith.dev/xyz
    stacks:
      - Python
      - Docker
      - Kubernetes
  - backgroundColor: bg-green-50/50
    borderColor: border-green-200
    name: Personal Portfolio Website
    description: Developed a personal portfolio website to showcase projects and skills.
    websites:
      - https://johnsmith.dev
    stacks:
      - HTML
      - CSS
      - JavaScript
      - Vue.js
