# This is a sample yaml!
# Create new yaml according to your own information and language, then configure on `/app/app.config.ts`.
# 
# IMPORTANT: all keys must be in camelCase.

title: John Smith
badges:
  - text: Software Engineer
    color: bg-blue-500
  - text: Open Source Enthusiast
    color: bg-green-500
summary: >
  Passionate software engineer with over 8 years of experience in developing scalable web applications and contributing to open source projects. Adept at working in fast-paced environments and collaborating with cross-functional teams to
  deliver high-quality software solutions.
contact:
  phone: +1 555-123-4567
  email: john.smith@example.io
location: San Francisco, CA, USA
websites:
  - https://johnsmith.dev
  - https://linkedin.com/in/johnsmith

education:
  - institution: Massachusetts Institute of Technology
    location: Cambridge, MA, USA
    degree: Master of Science in Computer Science
    gpa: 3.9/4.0
  - institution: University of California, Berkeley
    location: Berkeley, CA, USA
    degree: Bachelor of Science in Computer Science
    gpa: 3.8/4.0

skill:
  - category: Programming Languages
    list:
      - Python
      - JavaScript
      - Go
      - Java
  - category: Frameworks & Libraries
    list:
      - React
      - Node.js
      - Django
      - Spring Boot
  - category: Tools & Platforms
    list:
      - Docker
      - Kubernetes
      - AWS
      - GitHub Actions

work:
  - company: Tech Innovators Inc.
    position: Senior Software Engineer
    description: Led a team of developers in creating cloud-native applications and microservices.
    location: Chicago, IL, USA
    achievements:
      - name: Project Alpha
        descriptions:
          - Developed a high-availability microservices architecture that reduced downtime by 30%.
          - Implemented CI/CD pipelines, decreasing deployment times from hours to minutes.
      - name: System Optimization
        descriptions:
          - Optimized database queries, resulting in a 25% performance improvement for key applications.
          - Mentored junior developers, fostering a culture of continuous learning and improvement.
  - company: Web Solutions LLC
    position: Software Engineering Intern
    description: Assisted in developing web applications and improving user interfaces.
    location: New York, NY, USA
    achievements:
      - name: UI Enhancement
        descriptions:
          - Redesigned key components of the user interface, enhancing user experience and engagement.
          - Collaborated with senior developers to implement new features based on client feedback.

project:
  - name: Open Source Library XYZ
    description: Created and maintained an open-source library for data processing, used by thousands of developers worldwide.
    websites:
      - https://johnsmith.dev/xyz
    stacks:
      - Python
      - Docker
      - Kubernetes
  - name: Personal Portfolio Website
    description: Developed a personal portfolio website to showcase projects and skills.
    websites:
      - https://johnsmith.dev
